import Head from 'next/head'
import { useEffect, useState } from 'react'
import Loading from '../components/Loading'
import Login from '../components/Login'
import UserDashboard from '../components/UserDashboard'
import { useAuth } from '../context/AuthContext'


export default function Home() {

  const [loading, setLoading] = useState(true)
  const { currentUser } = useAuth()

  return (
    <>
      <Head>
        <title>NEXLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentUser ?
        <UserDashboard loading={loading} setLoading={setLoading} />
        :
        <Login setLoading={setLoading} />}
    </ >
  )
}
